const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { loginAs } = require('./staff-helpers.cjs');
const output = path.resolve(__dirname, '../artifacts/assistant');
const url = process.env.UX_BASE_URL || 'http://127.0.0.1:3000/';
const storageKey = 'greencity.assistant.v1:demo-accountant';
fs.mkdirSync(output, { recursive: true });

(async () => {
  const browser = await chromium.launch({ headless: true, channel: 'msedge' });
  const checks = [];
  const errors = [];
  const check = (name, value = true) => { assert.ok(value, name); checks.push(name); console.log(`PASS ${name}`); };
  const createPage = async setup => {
    const context = await browser.newContext({ viewport: { width: 1440, height: 900 }, locale: 'vi-VN' });
    if (setup) await context.addInitScript(setup);
    const page = await context.newPage();
    page.on('pageerror', error => errors.push(error.message));
    await page.goto(url);
    await page.waitForLoadState('networkidle');
    await loginAs(page, 'accountant');
    return page;
  };
  try {
    const page = await createPage(() => {
      Object.defineProperty(navigator, 'clipboard', { configurable: true, value: { writeText: async text => { window.testClipboard = text; } } });
    });
    const panel = page.getByRole('dialog', { name: 'Green Assistant', exact: true });
    const input = page.getByRole('textbox', { name: 'Nhập tin nhắn cho Green Assistant' });
    const log = page.getByRole('log', { name: 'Nội dung trò chuyện' });
    const open = () => page.getByRole('button', { name: /Mở Green Assistant/ }).click();
    const settle = async () => {
      await page.waitForFunction(() => !document.querySelector('.assistant-message.is-pending'));
    };
    const send = async text => { await input.fill(text); await input.press('Enter'); };
    const atBottom = () => log.evaluate(el => el.scrollHeight - el.scrollTop - el.clientHeight < 4);
    const shot = name => page.screenshot({ path: path.join(output, name) });
    console.log(JSON.stringify({ headings: await page.locator('h1').allTextContents(), assistantControls: await page.locator('.green-assistant button:visible').allTextContents() }));
    check('pet launcher is visible on desktop', await page.getByRole('button', { name: 'Mở Green Assistant', exact: true }).isVisible());
    await shot('01-pet-launcher.png');
    await open();
    check('chat opens and focuses composer', await input.evaluate(element => element === document.activeElement));
    check('empty chat has two relevant suggestions', await panel.locator('.assistant-suggestions button').count() === 2);
    check('empty message cannot be sent', await panel.getByRole('button', { name: 'Gửi tin nhắn', exact: true }).isDisabled());
    await shot('02-welcome.png');
    await panel.screenshot({ path: path.join(output, 'GreenAssistant.png') });
    await input.fill('Dòng thứ nhất');
    await input.press('Shift+Enter');
    await input.press('n');
    check('Shift Enter inserts a newline without sending', await input.inputValue() === 'Dòng thứ nhất\nn' && await log.locator('article').count() === 0);
    await input.fill('Xin chào');
    await input.dispatchEvent('keydown', { key: 'Enter', code: 'Enter', isComposing: true });
    check('IME Enter does not send prematurely', await log.locator('article').count() === 0);
    await input.press('Enter');
    check('Enter sends once and shows user message', await log.locator('.assistant-message-user').count() === 1);
    check('visible typing status has the required wording', await panel.getByRole('status').filter({ hasText: 'Green Assistant đang trả lời...' }).isVisible());
    check('processing has busy state and disabled send', await log.getAttribute('aria-busy') === 'true' && await panel.getByRole('button', { name: 'Đang xử lý câu hỏi' }).isDisabled());
    await input.fill('Câu tiếp theo chưa gửi');
    await input.press('Enter');
    check('busy state blocks duplicate send but keeps draft', await log.locator('.assistant-message-user').count() === 1 && await input.inputValue() === 'Câu tiếp theo chưa gửi');
    await shot('03-loading.png');
    await settle();
    check('user and assistant have visually different bubbles', await log.locator('.assistant-message-user .assistant-message-bubble').evaluate(el => getComputedStyle(el).backgroundColor) !== await log.locator('.assistant-message-assistant .assistant-message-bubble').evaluate(el => getComputedStyle(el).backgroundColor));
    check('reply does not erase next question draft', await input.inputValue() === 'Câu tiếp theo chưa gửi');
    check('new response auto-scrolls to bottom', await atBottom());
    await panel.getByRole('button', { name: 'Sao chép câu trả lời', exact: true }).click();
    check('copy writes exact answer and shows confirmation', await page.evaluate(() => window.testClipboard.includes('chưa kết nối mô hình AI')) && await panel.getByText('Đã sao chép', { exact: true }).isVisible());
    await input.fill('');
    await shot('04-conversation.png');
    await panel.getByRole('button', { name: 'Thu gọn Green Assistant' }).click();
    check('close returns focus to pet', await page.getByRole('button', { name: 'Mở Green Assistant', exact: true }).evaluate(el => el === document.activeElement));
    await open();
    check('close and reopen retains conversation', await log.locator('.assistant-message-user').count() === 1);
    await page.reload();
    await open();
    check('history survives reload', await log.locator('.assistant-message-user').count() === 1 && await log.locator('.assistant-message-assistant.is-complete').count() === 1);
    await panel.getByRole('button', { name: 'Tạo cuộc trò chuyện mới' }).click();
    check('new conversation starts empty', await log.locator('article').count() === 0);
    await panel.getByRole('button', { name: 'Lịch sử trò chuyện' }).click();
    check('new conversation keeps the previous conversation', await panel.locator('.assistant-history-item').count() === 2);
    await panel.getByRole('button', { name: /Xin chào/ }).click();
    check('history entry reopens original messages', await log.locator('.assistant-message-user').count() === 1);
    await send('thử lỗi');
    await settle();
    check('error explains what happened and exposes retry', await panel.getByRole('alert').filter({ hasText: 'lỗi mô phỏng' }).isVisible());
    await shot('05-retry-error.png');
    await panel.getByRole('button', { name: 'Gửi lại câu hỏi', exact: true }).click();
    await settle();
    check('retry succeeds without duplicating the user message', await log.locator('.assistant-message-user').count() === 2 && await log.getByText(/Đã gửi lại thành công/).isVisible());
    await input.fill('Bản nháp cần giữ');
    await panel.getByRole('button', { name: 'Tạo cuộc trò chuyện mới' }).click();
    await send('Hướng dẫn kiểm tra phiếu hoàn tiền');
    await panel.getByRole('button', { name: 'Tạo cuộc trò chuyện mới' }).click();
    await page.waitForTimeout(1250);
    check('late reply never leaks into the new conversation', await log.locator('article').count() === 0);
    await panel.getByRole('button', { name: 'Lịch sử trò chuyện' }).click();
    await shot('06-history.png');
    await panel.getByRole('button', { name: /Hướng dẫn kiểm tra phiếu hoàn tiền/ }).click();
    check('late reply is saved to its original conversation', await log.locator('.assistant-message-assistant.is-complete').count() === 1);
    await send('Thông báo');
    await page.reload();
    await open();
    check('reload during processing offers retry, not infinite loading', await panel.getByRole('alert').filter({ hasText: 'gián đoạn' }).isVisible() && await log.locator('.is-pending').count() === 0);
    await panel.getByRole('button', { name: 'Gửi lại câu hỏi', exact: true }).click();
    await settle();
    check('interrupted question can be retried', await log.locator('.is-error').count() === 0);
    await page.evaluate(() => { navigator.clipboard.writeText = async () => { throw new Error('Clipboard denied'); }; });
    await panel.getByRole('button', { name: 'Sao chép câu trả lời', exact: true }).last().click();
    check('clipboard failure provides a manual recovery path', await panel.getByRole('status').filter({ hasText: 'Ctrl+C' }).isVisible());

    await send('Công việc quá hạn');
    await settle();
    await input.fill('Thông báo');
    await input.press('Enter');
    await log.evaluate(el => { el.scrollTop = 0; });
    await settle();
    check('reading older messages does not force-scroll', await log.evaluate(el => el.scrollTop) === 0 && await panel.getByRole('button', { name: 'Tin nhắn mới nhất' }).isVisible());
    await panel.getByRole('button', { name: 'Tin nhắn mới nhất' }).click();
    check('new-message shortcut returns to latest', await atBottom());
    await input.fill('x'.repeat(2001));
    await input.press('Enter');
    check('oversized input is retained with clear validation', await panel.getByRole('alert').filter({ hasText: 'Câu hỏi quá dài' }).isVisible() && (await input.inputValue()).length === 2001);
    await input.fill('');
    await page.emulateMedia({ reducedMotion: 'reduce' });
    await send('Thông báo');
    check('reduced motion stops loading animation without hiding state', await panel.locator('.assistant-spinner').first().evaluate(el => getComputedStyle(el).animationName === 'none'));
    await settle();

    for (const [width, height] of [[1920, 1080], [1440, 900], [1280, 720], [1024, 768], [800, 600], [720, 450]]) {
      await page.setViewportSize({ width, height });
      check(`chat stays inside ${width}x${height}`, await panel.evaluate(el => { const rect = el.getBoundingClientRect(); return rect.left >= 0 && rect.top >= 0 && rect.right <= innerWidth && rect.bottom <= innerHeight; }));
      check(`composer visible at ${width}x${height}`, await input.evaluate(el => { const input = el.getBoundingClientRect(); const panel = document.querySelector('.assistant-panel').getBoundingClientRect(); return input.top >= panel.top && input.bottom <= panel.bottom; }));
      if (width === 1280 || width === 800) await shot(`07-chat-${width}.png`);
    }
    await page.setViewportSize({ width: 1280, height: 720 });
    await panel.getByRole('button', { name: 'Thu gọn Green Assistant' }).click();
    await page.getByRole('navigation', { name: 'Điều hướng chính' }).getByRole('button', { name: 'Phiếu hoàn tiền & Hoá đơn', exact: true }).click();
    check('pet does not overlap refund action bar', await page.locator('.assistant-launcher').evaluate(el => el.getBoundingClientRect().bottom <= document.querySelector('.form-action-bar').getBoundingClientRect().top));
    await open();
    check('chat does not overlap refund action bar', await panel.evaluate(el => el.getBoundingClientRect().bottom <= document.querySelector('.form-action-bar').getBoundingClientRect().top));
    await shot('08-refund-assistant.png');
    await input.press('Escape');
    check('Escape minimizes assistant', !await panel.isVisible());
    await open();
    await send('Công việc quá hạn');
    await panel.getByRole('button', { name: 'Thu gọn Green Assistant' }).click();
    await page.getByRole('button', { name: 'Mở Green Assistant, có phản hồi mới', exact: true }).waitFor();
    check('minimized companion signals a new response');
    await open();
    check('reopening shows the response received while minimized', await log.locator('.assistant-message-assistant.is-complete').count() > 0);

    const timedOut = await createPage(() => {
      const setTimer = window.setTimeout.bind(window);
      window.setTimeout = (callback, delay, ...args) => setTimer(callback, delay === 1100 ? 30000 : delay === 15000 ? 100 : delay, ...args);
    });
    await timedOut.getByRole('button', { name: 'Mở Green Assistant', exact: true }).click();
    await timedOut.getByRole('textbox', { name: 'Nhập tin nhắn cho Green Assistant' }).fill('Kiểm tra timeout');
    await timedOut.getByRole('button', { name: 'Gửi tin nhắn', exact: true }).click();
    await timedOut.getByRole('alert').filter({ hasText: 'Hệ thống xử lý quá lâu' }).waitFor();
    check('request timeout exits loading with a retry action', await timedOut.getByRole('button', { name: 'Gửi lại câu hỏi' }).isVisible());

    const blocked = await createPage(() => { Storage.prototype.setItem = () => { throw new Error('Quota exceeded'); }; });
    await blocked.getByRole('button', { name: 'Mở Green Assistant', exact: true }).click();
    check('history write failure is visible', await blocked.getByRole('alert').filter({ hasText: 'Không lưu được lịch sử trên máy' }).isVisible());
    const corrupt = await createPage(() => { localStorage.setItem('greencity.assistant.v1:demo-accountant', '{broken'); });
    await corrupt.getByRole('button', { name: 'Mở Green Assistant', exact: true }).click();
    check('corrupt history is not overwritten', await corrupt.evaluate(key => localStorage.getItem(key), storageKey) === '{broken' && await corrupt.getByRole('alert').filter({ hasText: 'Không đọc được lịch sử' }).isVisible());
    await page.evaluate(() => window.dispatchEvent(new StorageEvent('storage', { key: 'greencity.assistant.v1:demo-accountant', newValue: '{another-window}' })));
    check('another window cannot silently overwrite this conversation', await page.getByRole('alert').filter({ hasText: 'tạm ngừng lưu để tránh ghi đè' }).isVisible());
    check('no runtime JavaScript errors', errors.length === 0);
    fs.writeFileSync(path.join(output, 'test-results.json'), JSON.stringify({ passed: checks.length, checks, errors }, null, 2));
    console.log(`ASSISTANT UX: ${checks.length} checks passed.`);
  } catch (error) { console.error('Runtime errors:', errors); throw error; }
  finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
